stream_source:
  # - "Big buck bunny": "rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov"
  # - "Dog day care": "http://76.174.92.213/mjpg/video.mjpg"
  - "Outside Office": "http://outside_office_stream:6420/cam.mjpg"
  - "Traffic Cam": "http://traffic_monitor_stream:6420/cam.mjpg"
  - "Parking Lot": "http://school_parkinglot_stream:6420/cam.mjpg"
  - "Building": "http://building_stream:6420/cam.mjpg"
docker_compose_location: "./static/docker-compose.yml"